apiVersion: skaffold/v1
kind: Config
metadata:
  name: iplant-email
deploy:
  kubectl:
    manifests:
    - k8s/iplant-email.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/iplant-email
  local: {}
